/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _IDL_H_RPCGEN
#define _IDL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct mpc_struct {
	int graph_id;
	int args[3];
};
typedef struct mpc_struct mpc_struct;

#define COMPUTE 456123789
#define COMPUTE_VERS 6

#if defined(__STDC__) || defined(__cplusplus)
#define ADD_GRAPH 1
extern  void * add_graph_6(mpc_struct *, CLIENT *);
extern  void * add_graph_6_svc(mpc_struct *, struct svc_req *);
#define ADD_EGDE 2
extern  void * add_egde_6(mpc_struct *, CLIENT *);
extern  void * add_egde_6_svc(mpc_struct *, struct svc_req *);
#define GET_MST 3
extern  long * get_mst_6(mpc_struct *, CLIENT *);
extern  long * get_mst_6_svc(mpc_struct *, struct svc_req *);
extern int compute_6_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD_GRAPH 1
extern  void * add_graph_6();
extern  void * add_graph_6_svc();
#define ADD_EGDE 2
extern  void * add_egde_6();
extern  void * add_egde_6_svc();
#define GET_MST 3
extern  long * get_mst_6();
extern  long * get_mst_6_svc();
extern int compute_6_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_mpc_struct (XDR *, mpc_struct*);

#else /* K&R C */
extern bool_t xdr_mpc_struct ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_IDL_H_RPCGEN */
