/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "IDL.h"

void *
add_graph_6_svc(mpc_struct *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}

void *
add_egde_6_svc(mpc_struct *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}

long *
get_mst_6_svc(mpc_struct *argp, struct svc_req *rqstp)
{
	static long  result;

	/*
	 * insert server code here
	 */

	return &result;
}
