/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "IDL.h"

bool_t
xdr_mpc_struct (XDR *xdrs, mpc_struct *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, (1 +  3 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->graph_id))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->args, 3,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->graph_id);
			{
				register int *genp;

				for (i = 0, genp = objp->args;
					i < 3; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, (1 +  3 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->graph_id))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->args, 3,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			objp->graph_id = IXDR_GET_LONG(buf);
			{
				register int *genp;

				for (i = 0, genp = objp->args;
					i < 3; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->graph_id))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->args, 3,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}
