/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "IDL.h"

void *
add_graph_6_svc(mpc_struct *argp, struct svc_req *rqstp)
{
	static char *result;
	printf("add graph called");
	/*
	 * insert server code here
	 */

	return (void *)&result;
}

void *
add_egde_6_svc(mpc_struct *argp, struct svc_req *rqstp)
{
	static char *result;

	printf("add edge called");
	/*
	 * insert server code here
	 */

	return (void *)&result;
}

long *
get_mst_6_svc(mpc_struct *argp, struct svc_req *rqstp)
{
	static long result;

	printf("get mst called");
	/*
	 * insert server code here
	 */

	return &result;
}
